// <auto-generated />
using System;
using LanguageLearning.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguageLearning.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LanguageLearningDbContext))]
    [Migration("20260610100410_NormalizeExistingUsersForSessionAuth")]
    partial class NormalizeExistingUsersForSessionAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanguageLearning.Domain.AIScoringResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrammarScore")
                        .HasColumnType("int");

                    b.Property<int>("NaturalnessScore")
                        .HasColumnType("int");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int");

                    b.Property<int>("SentencePracticeId")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VocabularyScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SentencePracticeId")
                        .IsUnique();

                    b.ToTable("AIScoringResults");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredXP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Earn your first 50 XP.",
                            IconUrl = "spark",
                            Name = "First Spark",
                            RequiredXP = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Keep a 7 day streak.",
                            IconUrl = "calendar",
                            Name = "Week Rhythm",
                            RequiredXP = 150
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pass 10 quizzes.",
                            IconUrl = "trophy",
                            Name = "Quiz Ace",
                            RequiredXP = 300
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Build daily conversation, core vocabulary, and confident pronunciation.",
                            IsPublished = true,
                            LanguageId = 1,
                            Level = "A1",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80",
                            Title = "English Starter Path"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Meetings, emails, presentations, and polite office conversation.",
                            IsPublished = true,
                            LanguageId = 1,
                            Level = "A2",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80",
                            Title = "Workplace English"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hiragana, greetings, and survival phrases for beginners.",
                            IsPublished = true,
                            LanguageId = 2,
                            Level = "A1",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
                            Title = "Japanese First Steps"
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlagIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            FlagIcon = "US",
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ja",
                            FlagIcon = "JP",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ko",
                            FlagIcon = "KR",
                            Name = "Korean"
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LessonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("XPReward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Say hello, introduce yourself, and answer simple questions.",
                            IsLocked = false,
                            LessonType = "Vocabulary",
                            SortOrder = 1,
                            Title = "Greetings and names",
                            UnitId = 1,
                            XPReward = 20
                        },
                        new
                        {
                            Id = 2,
                            Description = "Talk about countries, cities, and origin.",
                            IsLocked = true,
                            LessonType = "Speaking",
                            SortOrder = 2,
                            Title = "Where are you from?",
                            UnitId = 1,
                            XPReward = 25
                        },
                        new
                        {
                            Id = 3,
                            Description = "Order simple meals and describe preferences.",
                            IsLocked = true,
                            LessonType = "Listening",
                            SortOrder = 1,
                            Title = "Food and drinks",
                            UnitId = 2,
                            XPReward = 25
                        },
                        new
                        {
                            Id = 4,
                            Description = "Understand schedules, reports, and meeting language.",
                            IsLocked = false,
                            LessonType = "Grammar",
                            SortOrder = 1,
                            Title = "Meetings at work",
                            UnitId = 3,
                            XPReward = 30
                        },
                        new
                        {
                            Id = 5,
                            Description = "Read and recognize the first Japanese sounds.",
                            IsLocked = false,
                            LessonType = "Vocabulary",
                            SortOrder = 1,
                            Title = "Hiragana vowels",
                            UnitId = 4,
                            XPReward = 20
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.LessonStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("MinScoreToPass")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xem video va hoc tu vung trong ngu canh.",
                            IsRequired = true,
                            LessonId = 1,
                            MinScoreToPass = 0,
                            SortOrder = 1,
                            StepType = "Video",
                            Title = "Video gioi thieu"
                        },
                        new
                        {
                            Id = 2,
                            Description = "On tap toan bo tu moi cua bai.",
                            IsRequired = true,
                            LessonId = 1,
                            MinScoreToPass = 0,
                            SortOrder = 2,
                            StepType = "Flashcards",
                            Title = "Flashcard tu vung"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hoc mau cau gioi thieu ban than.",
                            IsRequired = true,
                            LessonId = 1,
                            MinScoreToPass = 0,
                            SortOrder = 3,
                            StepType = "Grammar",
                            Title = "Cau truc ngu phap"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dat it nhat 70 diem de tiep tuc.",
                            IsRequired = true,
                            LessonId = 1,
                            MinScoreToPass = 70,
                            SortOrder = 4,
                            StepType = "Quiz",
                            Title = "Quiz"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Van dung tu vung va ngu phap.",
                            IsRequired = true,
                            LessonId = 1,
                            MinScoreToPass = 70,
                            SortOrder = 5,
                            StepType = "Exercise",
                            Title = "Bai tap van dung"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gui cau cua ban de AI cham diem.",
                            IsRequired = true,
                            LessonId = 1,
                            MinScoreToPass = 70,
                            SortOrder = 6,
                            StepType = "SentencePractice",
                            Title = "Tu dat cau"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tong ket diem, XP va tien do.",
                            IsRequired = true,
                            LessonId = 1,
                            MinScoreToPass = 0,
                            SortOrder = 7,
                            StepType = "Result",
                            Title = "Ket qua"
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "My name is An.",
                            Explanation = "Use 'My name is...' for a natural self-introduction.",
                            LessonId = 1,
                            QuestionText = "Which sentence introduces your name?",
                            QuestionType = "MultipleChoice"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Rat vui duoc gap ban",
                            Explanation = "It is a polite phrase for first meetings.",
                            LessonId = 1,
                            QuestionText = "What does 'Nice to meet you' mean?",
                            QuestionType = "MultipleChoice"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "I am from Vietnam.",
                            Explanation = "Use 'I am from...' plus a place.",
                            LessonId = 2,
                            QuestionText = "Choose the correct answer: Where are you from?",
                            QuestionType = "Speaking"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "Han chot",
                            Explanation = "A deadline is the latest time work should be finished.",
                            LessonId = 4,
                            QuestionText = "What is a deadline?",
                            QuestionType = "Grammar"
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = false,
                            OptionText = "I am coffee.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = true,
                            OptionText = "My name is An.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            OptionText = "She from Japan.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            OptionText = "Tam biet",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            OptionText = "Rat vui duoc gap ban",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            OptionText = "Toi dang hoc",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = true,
                            OptionText = "I am from Vietnam.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            OptionText = "I from Vietnam.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            OptionText = "Vietnam from I.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            OptionText = "Phong hop",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            OptionText = "Han chot",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            OptionText = "Ngay nghi",
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.SentencePractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GrammarStructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonStepId")
                        .HasColumnType("int");

                    b.Property<string>("StudentSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonStepId");

                    b.HasIndex("UserId");

                    b.ToTable("SentencePractices");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Streak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastStudyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Streaks");
                });

            modelBuilder.Entity("LanguageLearning.Domain.StudentStepProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonStepId")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonStepId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentStepProgress");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            SortOrder = 1,
                            Title = "Meet People"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            SortOrder = 2,
                            Title = "Daily Life"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            SortOrder = 1,
                            Title = "Office Basics"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 3,
                            SortOrder = 1,
                            Title = "Kana Basics"
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentSessionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentLessonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCourses");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserLessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLessonProgress");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronunciation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Vocabulary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExampleSentence = "Hello, my name is Linh.",
                            LessonId = 1,
                            Meaning = "xin chao",
                            Pronunciation = "heh-low",
                            Word = "hello"
                        },
                        new
                        {
                            Id = 2,
                            ExampleSentence = "What is your name?",
                            LessonId = 1,
                            Meaning = "ten",
                            Pronunciation = "naym",
                            Word = "name"
                        },
                        new
                        {
                            Id = 3,
                            ExampleSentence = "I am from Vietnam.",
                            LessonId = 2,
                            Meaning = "den tu",
                            Pronunciation = "frum",
                            Word = "from"
                        },
                        new
                        {
                            Id = 4,
                            ExampleSentence = "The meeting starts at nine.",
                            LessonId = 4,
                            Meaning = "cuoc hop",
                            Pronunciation = "mee-ting",
                            Word = "meeting"
                        },
                        new
                        {
                            Id = 5,
                            ExampleSentence = "A sounds like ah.",
                            LessonId = 5,
                            Meaning = "am a trong hiragana",
                            Pronunciation = "a",
                            Word = "a"
                        });
                });

            modelBuilder.Entity("LanguageLearning.Domain.AIScoringResult", b =>
                {
                    b.HasOne("LanguageLearning.Domain.SentencePractice", "SentencePractice")
                        .WithOne("ScoringResult")
                        .HasForeignKey("LanguageLearning.Domain.AIScoringResult", "SentencePracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SentencePractice");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Course", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Language", "Language")
                        .WithMany("Courses")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Lesson", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Unit", "Unit")
                        .WithMany("Lessons")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LanguageLearning.Domain.LessonStep", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Lesson", "Lesson")
                        .WithMany("Steps")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LanguageLearning.Domain.LoginHistory", b =>
                {
                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany("LoginHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Payment", b =>
                {
                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Question", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LanguageLearning.Domain.QuestionOption", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LanguageLearning.Domain.SentencePractice", b =>
                {
                    b.HasOne("LanguageLearning.Domain.LessonStep", "LessonStep")
                        .WithMany()
                        .HasForeignKey("LessonStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonStep");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Streak", b =>
                {
                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.StudentStepProgress", b =>
                {
                    b.HasOne("LanguageLearning.Domain.LessonStep", "LessonStep")
                        .WithMany()
                        .HasForeignKey("LessonStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonStep");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Subscription", b =>
                {
                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Unit", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Course", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserAchievement", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserAnswer", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserCourse", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserLessonProgress", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany("LessonProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.UserSession", b =>
                {
                    b.HasOne("LanguageLearning.Domain.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Vocabulary", b =>
                {
                    b.HasOne("LanguageLearning.Domain.Lesson", "Lesson")
                        .WithMany("Vocabulary")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Course", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Language", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Lesson", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Steps");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LanguageLearning.Domain.SentencePractice", b =>
                {
                    b.Navigation("ScoringResult");
                });

            modelBuilder.Entity("LanguageLearning.Domain.Unit", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LanguageLearning.Domain.User", b =>
                {
                    b.Navigation("LessonProgress");

                    b.Navigation("LoginHistory");

                    b.Navigation("Sessions");

                    b.Navigation("UserCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
